import { describe, expect, it } from 'vitest';

import { renderShareHtml, type RenderInput } from './render.js';

/**
 * Core renderShareHtml tests — page chrome, text rendering, privacy,
 * non-message rows, XSS, truncation. Tool-folding + rewind cases live
 * in `render-rewind.test.ts`.
 */

function input(jsonl: string, overrides: Partial<RenderInput> = {}): RenderInput {
  return {
    jsonl,
    projectName: 'demo-proj',
    createdBy: 'alice',
    createdAt: 1_700_000_000_000,
    shareCode: '550e8400-e29b-41d4-a716-446655440000',
    ...overrides,
  };
}

describe('renderShareHtml', () => {
  it('produces a standalone HTML document with DOCTYPE + inline CSS + script', () => {
    const html = renderShareHtml(input(''));
    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('<style>');
    expect(html).toContain('<script>');
    expect(html).toContain('</html>');
  });

  it('renders user text via markdown (paragraph wrapping)', () => {
    const row = JSON.stringify({
      type: 'user',
      message: { role: 'user', content: 'hello world' },
    });
    const html = renderShareHtml(input(row));
    expect(html).toContain('<p>hello world</p>');
  });

  it('renders assistant text array part', () => {
    const row = JSON.stringify({
      type: 'assistant',
      message: {
        role: 'assistant',
        content: [{ type: 'text', text: 'response **bold**' }],
      },
      timestamp: '2024-01-01T00:00:00Z',
    });
    const html = renderShareHtml(input(row));
    expect(html).toContain('<strong>bold</strong>');
    expect(html).toMatch(/article class="msg assistant"/);
  });

  it('drops assistant thinking blocks (privacy)', () => {
    const row = JSON.stringify({
      type: 'assistant',
      message: {
        role: 'assistant',
        content: [
          { type: 'thinking', thinking: 'INTERNAL_COT_LEAK' },
          { type: 'text', text: 'visible response' },
        ],
      },
    });
    const html = renderShareHtml(input(row));
    expect(html).not.toContain('INTERNAL_COT_LEAK');
    expect(html).toContain('visible response');
  });

  it('skips permission-mode / file-history-snapshot / system / attachment rows', () => {
    const lines = [
      JSON.stringify({ type: 'permission-mode', permissionMode: 'default' }),
      JSON.stringify({ type: 'file-history-snapshot', messageId: 'm1' }),
      JSON.stringify({
        type: 'system',
        subtype: 'reminder',
        content: 'sysnoise',
      }),
      JSON.stringify({ type: 'attachment', attachment: { path: '/etc/x' } }),
    ];
    const html = renderShareHtml(input(lines.join('\n')));
    expect(html).not.toContain('sysnoise');
    expect(html).toContain('（无内容）');
  });

  it('skips system caveat user messages (local-command-caveat)', () => {
    const row = JSON.stringify({
      type: 'user',
      message: {
        role: 'user',
        content:
          '<local-command-caveat>Caveat: messages generated by user while running local commands</local-command-caveat>',
      },
    });
    const html = renderShareHtml(input(row));
    expect(html).not.toContain('Caveat:');
    expect(html).toContain('（无内容）');
  });

  it('escapes raw HTML in text + share code + project name (XSS protection)', () => {
    const row = JSON.stringify({
      type: 'user',
      message: { role: 'user', content: '<script>alert("xss")</script>' },
    });
    const html = renderShareHtml(
      input(row, {
        projectName: '<x>',
        shareCode: 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee',
      }),
    );
    expect(html).not.toMatch(/<script>alert/);
    expect(html).toContain('&lt;script&gt;');
    expect(html).toContain('&lt;x&gt;');
    expect(html).toContain('aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee');
  });

  it('survives malformed jsonl lines (skip + continue)', () => {
    const lines = [
      'not json',
      JSON.stringify({
        type: 'user',
        message: { role: 'user', content: 'good' },
      }),
      '{ "broken',
    ];
    const html = renderShareHtml(input(lines.join('\n')));
    expect(html).toContain('<p>good</p>');
  });

  it('strips tool_use bodies entirely (only footer count survives)', () => {
    // followed up by "完全不显示": tool I/O
    // never appears in HTML. Even huge tool inputs/outputs drop to
    // zero bytes in the rendered share.
    const big = 'x'.repeat(5000);
    const bigInput = { huge: 'y'.repeat(5000) };
    const lines = [
      JSON.stringify({
        type: 'assistant',
        message: {
          role: 'assistant',
          content: [{ type: 'tool_use', id: 't', name: 'Bash', input: bigInput }],
        },
      }),
      JSON.stringify({
        type: 'user',
        message: {
          role: 'user',
          content: [
            { type: 'tool_result', tool_use_id: 't', content: big },
          ],
        },
      }),
    ];
    const html = renderShareHtml(input(lines.join('\n')));
    expect(html).not.toContain('xxxx');
    expect(html).not.toContain('yyyy');
    expect(html).not.toContain('<details');
    expect(html).toContain('<div class="tools-footer">1 tool used</div>');
  });

  it('sets noindex meta + footer share code for traceability', () => {
    const code = 'cccccccc-cccc-4ccc-8ccc-cccccccccccc';
    const html = renderShareHtml(input('', { shareCode: code }));
    expect(html).toContain('<meta name="robots" content="noindex, nofollow">');
    expect(html).toContain(code);
  });
});
