export type DeviceStatus = 'active' | 'revoked';

export interface Device {
  /** UUIDv4. */
  readonly id: string;
  /**
   * m-multi-user: User.id this device belongs to. m-user-symmetric reframe:
   * data layer is symmetric — any user kind may be referenced here, but
   * pair policy currently restricts pair-time assignment to the owner
   * (CLI approve uses owner.id). Legacy records (pre-multi-user) load with
   * the fallback `DeviceStoreOptions.ownerId`.
   */
  readonly userId: string;
  /** User-provided label (not unique). */
  readonly label: string;
  /** Base64url-encoded WebAuthn credential id (the "rawId" round-trip). */
  readonly credentialId: string;
  /** Base64url-encoded COSE public key. */
  readonly publicKey: string;
  /** WebAuthn signature counter; monotonically increases with use. */
  readonly counter: number;
  /** epoch-ms when first paired. */
  readonly createdAt: number;
  /** epoch-ms of most recent successful login; null until first login. */
  readonly lastUsedAt: number | null;
  readonly status: DeviceStatus;
}

export type PendingStatus = 'awaiting-registration' | 'awaiting-approval' | 'approved' | 'rejected';

export interface PendingPair {
  /** Random opaque id; the browser polls this for status. */
  readonly pendingId: string;
  readonly label: string;
  /** Base64url challenge generated by generateRegistrationOptions. */
  readonly challenge: string;
  /**
   * Stage marker.
   * - 'awaiting-registration': browser hasn't called register-complete yet.
   * - 'awaiting-approval':     browser submitted attestation, mac CLI approve hasn't run.
   * - 'approved':              CLI approved, device created, sessionId issued.
   * - 'rejected':              CLI rejected (or pending expired and was cleaned up).
   */
  readonly status: PendingStatus;
  /** epoch-ms when register-init was called. */
  readonly createdAt: number;
  /**
   * Set when status becomes 'approved'; the browser long-polling for status
   * picks this up and uses it to set its cookie (one-shot).
   */
  readonly issuedSessionId: string | null;
  /**
   * Set when status becomes 'approved' so /api/auth/register-status can echo
   * the device id back to the browser without a second lookup.
   */
  readonly issuedDeviceId: string | null;
  /** Snapshot fields used by the mac CLI to decide whether to approve. */
  readonly remoteAddr: string | null;
  readonly userAgent: string | null;
}

export interface Session {
  /** Random opaque session id; lives in the cookie. */
  readonly sessionId: string;
  readonly deviceId: string;
  readonly createdAt: number;
  readonly lastUsedAt: number;
}

export interface LoginChallenge {
  readonly tempId: string;
  readonly deviceId: string;
  readonly challenge: string;
  readonly createdAt: number;
}
