#!/usr/bin/env node
import { stdout } from 'node:process';
import { runApprove } from './cli/approve.js';
import { runDevices } from './cli/devices.js';
import { runRevoke } from './cli/revoke.js';
import { runServe } from './cli/serve.js';
import { logger } from './log.js';

const HELP = `ccanywhere — cc CLI exposed over the web

usage:
  ccanywhere [serve]                    start the HTTP/WS server (default)
  ccanywhere approve                    interactively approve pending device pair requests
  ccanywhere devices                    list registered devices
  ccanywhere revoke <device-id>         revoke a device (drops sessions, blocks future logins)
  ccanywhere help                       show this help

config: ~/.config/ccanywhere/config.json
device store: ~/.config/ccanywhere/devices.json
cli token: ~/.config/ccanywhere/cli-token (auto-generated by \`serve\`)
`;

async function dispatch(argv: ReadonlyArray<string>): Promise<void> {
  const cmd = argv[0] ?? 'serve';
  switch (cmd) {
    case 'serve':
      return runServe();
    case 'approve':
      return runApprove();
    case 'devices':
      return runDevices();
    case 'revoke':
      return runRevoke(argv[1]);
    case 'help':
    case '--help':
    case '-h':
      stdout.write(HELP);
      return;
    default:
      stdout.write(`unknown subcommand: ${cmd}\n\n${HELP}`);
      process.exit(2);
  }
}

void dispatch(process.argv.slice(2)).catch((err: unknown) => {
  logger.fatal({ err }, 'fatal cli error');
  process.exit(1);
});
